apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: devops091/dotnet-app:39
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: https-cert-secret
              key: password
        volumeMounts:
        - mountPath: /app/certs
          name: cert-volume
      volumes:
      - name: cert-volume
        secret:
          secretName: https-cert-secret
      imagePullSecrets:
      - name: sample-app
