apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      imagePullSecrets:
        - name: my-registry-secret  # Reference to your Docker registry secret
      containers:
      - name: sample-app
        image: <docker-image>
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cert-volume
          mountPath: /app/certs
      volumes:
      - name: cert-volume
        secret:
          secretName: https-cert-secret
