apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080  # Replace with your preferred node port
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30443  # Replace with your preferred node port
  type: NodePort
